.github/workflows/go.yml, README.md
Adding badges for Build, License, and GitHub Pages to README.
=> Add badges.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
This PR improves the issue templates by:
- Updating the description (`about`) of each issue template
- Adding a `config.yml` which is used to disable blank issues
- Adding a `question.md` for questions
- Adding predefined labels to issues
=> Improve issue templates.

cmd/root.go, pkg/http/utils.go
=> Init random seed only once

README.md
=> Add link to docker in main readme

docs/about/introduction.md, website/pages/en/index.js
- Tests GitHub Action for publishing docs
- Adds feature that allows random elements in requests to list of features provided by Mittens
=> Update docs to test action.

docs/about/getting-started.md
- Dummy update to trigger publish action
=> Update docs to trigger action.

.github/workflows/go.yml, Dockerfile, Makefile, docs/installation/building.md
- Fixes the build commands in the docs and Dockerfile
=> [30] Fix build commands.

.dependabot/config.yml
- Enable [Dependabot](https://dependabot.com/) for dependency updates.
=> Enable Dependabot for dependency updates.

website/package.json, website/yarn.lock
- There was a security vulnerability in 1.0.0<=minimist< 1.2.3
=> Update JS dependencies.

README.md
Adding link to the blogpost about Mittens from EG tech blog.
=> Adding link to the blog post about Mittens

pkg/grpc/utils.go, pkg/grpc/utils_test.go, pkg/http/utils.go, pkg/http/utils_test.go, pkg/placeholders/utils.go, pkg/placeholders/utils_test.go
Add suport for placeholders for grpc. Fixes #94
=> Add support for placeholders for grpc

docs/about/getting-started.md
Update placeholders section (1 level up) so that it shows in the table of contents
=> Update placeholders section

cmd/flags/file_probe.go, cmd/root.go, docs/about/getting-started.md
Drops support for probe overrides.
#102
=> [#102] Drop probe overrides.

website/package.json
- Fixes CVE-2020-8244 in bl library. This is only used in the docs.
=> Update bl library in docs to fix CVE-2020-8244.

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/gh-pages.yml, .github/workflows/go.yml, docs/installation/building.md
=> Rename primary branch to main

docs/installation/running.md
Please verify that:
Improves documentation for the naïve copy-pasters out there like myself.
#143 
```shell
❯ make unit-tests
?   	mittens	[no test files]
?   	mittens/cmd	[no test files]
ok  	mittens/cmd/flags	0.225s
?   	mittens/fixture	[no test files]
ok  	mittens/pkg/grpc	0.200s
ok  	mittens/pkg/http	0.228s
ok  	mittens/pkg/placeholders	0.517s
?   	mittens/pkg/probe	[no test files]
?   	mittens/pkg/response	[no test files]
ok  	mittens/pkg/safe	0.286s
ok  	mittens/pkg/util	0.411s
?   	mittens/pkg/warmup	[no test files]
```
=> Fix Kubernetes-related documentation for running.md #143

Dockerfile
=> Run docker as non root

.github/workflows/docker-build-push.yml, .github/workflows/go.yml, Dockerfile, README.md
Update Go to 16 and Alpine to 3.12
=> Update docker dependencies

.github/workflows/docker-build-push.yml
- Update docker push github action
Note: besides tagging the image this will also add labels to the Docker image:
=> Update docker push github action

.github/workflows/codeql-analysis.yml
Run codeql only for push/pull for main branch
=> Run codeql only for push/pull for main branch

internal/pkg/internal/utils_test.go, internal/pkg/probe/file_test.go
add unit test to internal/pkg/internal/utils.go and internal/pkg/probe/file.go solving issue #172
=> add unit test issue #172

cmd/flags/http_test.go
* Added invalid format test for toHTTPRequest function
* Added invalid Body test for toHTTPRequest function
* Added invalid Method test for toHTTPRequest function
=> testing http request format

.github/workflows/docker-build-push.yml
- Update docker build to publish multi arch images
- Fixes #182
=> Update docker build to publish multi arch images

docs/installation/running.md
Fixing a typo in the documentation
=> Fix typo in docs

.github/workflows/go.yml
Updates actions/checkout to v2 
#210
=> Update checkout to v2.

Dockerfile, README.md, docs/installation/building.md, go.mod
=> Bump to go 1.16

.github/workflows/go.yml, Dockerfile, README.md, docs/installation/building.md, go.mod
=> Bump to go 1.19

internal/pkg/grpc/client.go
The `-target-insecure` flag is not working for gRPC calls, this was removed from https://github.com/ExpediaGroup/mittens/pull/248 PR, so have re-added it and amended the logic. More info for client authentication can be found [here](https://grpc.io/docs/guides/auth/#go) 
* Re-added insecure function and corrected the logic
* Added more information for connection errors
* Replaced deprecated functions
https://github.com/ExpediaGroup/mittens/issues/287
=> Fixed insecure for gRPC
