cmd/root.go, pkg/warmup/target.go, pkg/warmup/warmup.go
This change fixes a couple of issues that would result to warmup exit / non-successful termination in case of errors.
`log.Fatal` should never be called since this would kill the container which in its turn would cause pod restarts if running in K8S.
Also, errors when running the warmup vs the target readiness url were not propagated all the way up to the main method. This meant that warmup would continue its work (i.e. sending requests).
=> Fix issue where warmup would exit when there was an error.

cmd/flags/http.go, cmd/flags/http_test.go, cmd/flags/target.go, docs/about/getting-started.md, pkg/http/client.go, pkg/warmup/target.go, pkg/warmup/warmup.go
Support for placeholders for dates. Can be used in the url or body of a request.
Example:
- `post:/foo:{"date": "{today}"}`
=> Support for placeholders for dates

.github/workflows/go.yml
Currently when someone raises a PR from a fork GitHub Actions are not triggered.
This is due to the fact that we rely on the `push` event which is only sent for the base repo.
For PR from forks to trigger Actions we need to use the [pull_request](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-events-for-forked-repositories) event.
=> Trigger Actions on pull_request event to include PRs from forks.

pkg/http/client.go, pkg/http/client_test.go
It is a common practice that API's return a meaningful body when the response is 4xx or 5xx, hence it makes sense to close the response body on those cases too.
Ping @nikos912000 @worldtiki
=> Close body on non 2xx

README.md
Fixes the link to supported flags in the readme. This section was moved to GitHub Pages but link was pointing to readme instead.
=> Fix link to flags in readme.

website/siteConfig.js
Adds search to docs using Algolia.
This is the suggested way to enable search in [Docusaurus](https://docusaurus.io/docs/en/search) docs.
Algolia is a free service which crawls the docs every 24 hours.
=> Add Algolia search.

cmd/flags/grpc.go, cmd/flags/grpc_test.go, cmd/flags/http.go, cmd/flags/root.go, cmd/flags/target.go, cmd/root.go, cmd/root_test.go, cmd/sample_configs.json, docs/about/getting-started.md, docs/installation/running.md, pkg/grpc/client.go, pkg/grpc/utils.go, pkg/grpc/utils_test.go, pkg/http/utils.go, pkg/http/utils_test.go, pkg/warmup/target.go, pkg/warmup/warmup.go
This PR:
-  Adds support for gRPC healthchecks as suggested in #28 
- Fixes a couple of issues on the gRPC client. In specific, we were only setting timeouts for the RPCs and not for establishing the connection.
- Moves a couple of snippets under `pkg`.
#28
=> [#28] Add support for gRPC health checks

cmd/flags/http.go, docs/about/getting-started.md, pkg/http/utils.go, pkg/http/utils_test.go
- Add support for random elements.
- This is useful to systems that use remote caches and where the warmup fails to exercise the paths for cache misses.
- {{currentDate|days+x,months+y,years+z}} - you can adjust the temporal offset by adding or subtracting days, months or years. The offsets are optional and can be removed.
- {{currentTimestamp}} - Time from Unix epoch in milliseconds.
- {{random|foo,bar,baz}} - Mittens will randomly select an element from the provided list, eg: one of foo, bar or baz. Special chars are not supported. Valid: [0-9A-Za-z_]
- {{range|min=x,max=y}} - both min and max are required arguments. Range is inclusive.
=> Add support for randomized elements

Makefile, docs/about/getting-started.md, pkg/http/utils.go, pkg/http/utils_test.go
It turns out that using double brackets is a bad idea when we mix this with helm templates (it tries to run the placeholders as functions and fails because "random", ... don't exist).
Since that is the primary use case (kube/helm) for this warmup i'm replacing those with single brackets.
=> Replacing double with single brackets

.github/workflows/gh-pages.yml
- GitHub Action for publishing docs
- Uses https://github.com/peaceiris/actions-gh-pages and the automatically created [GITHUB_TOKEN](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token) which now works for public repos as well 🎉
- Author of commit is the `eg-oss-ci` user
=> #36 GitHub Action for publishing docs.

.github/workflows/gh-pages.yml
- Action uses the `projectName` from [here](https://github.com/ExpediaGroup/mittens/blob/06bd2db8e4770cdada4bcdbe41e25332cbdacd68/website/siteConfig.js#L32), not the repo name
=> Fix project name in publish directory used in action.

Makefile, README.md, cmd/flags/root.go, cmd/root_test.go, cmd/sample_configs.json, docs/about/getting-started.md, docs/installation/running.md, pkg/warmup/warmup.go
Rename flag -timeout-seconds to -max-duration-seconds for better understanding of what it is
#30
=> [#30] Rename flag -timeout-seconds to -max-duration-seconds

cmd/flags/root.go, cmd/flags/target.go, docs/about/getting-started.md, docs/installation/running.md
Drops support for `target-readiness-timeout-seconds`.
#59
=> [#59] Drop support for target-readiness-timeout-seconds.

.github/dependabot.yml
Enables GitHub Actions updates using Dependabot.
#74
=> [#74] Enable updates of GitHub Actions using Dependabot.

README.md
Updated `target-readiness-path` to `target-readiness-http-path` in README
=> Fix target-readiness-http-path flag name in readme

README.md, docs/installation/running.md
Improve how to run docs when using docker locally:
- Do not mention only Mac
- Add http prefix so it's clearer what value to use
- Make `host.docker.internal` the first choice
- Remove deprecated values `docker.for.xxx.localhost`
=> Improve how to run doc when using docker locally

cmd/flags/root.go, cmd/flags/target.go, cmd/root.go, cmd/root_test.go, pkg/grpc/client.go, pkg/http/client.go, pkg/warmup/target.go, pkg/warmup/warmup.go
- Fixes issue where mittens wouldn't establish connection to the gRPC server. This would cause a panic error (#89).
- Adds logic to avoid spinning up the corresponding goroutines for HTTP and gRPC if there are no requests of that type.
- Adds integration tests for gRPC (#90).
- Fixes the gRPC readiness functionality. The timeout for that would be 0 since we were relying on the removed `-target-readiness-timeout-seconds`. 
#89 #90
=> [#89][#90] Fix grpc client. Add integration tests for grpc.

docs/about/getting-started.md, pkg/http/utils.go, pkg/http/utils_test.go
Fixes #92
`{$currentDate|days+x,months+y,years+z,format=yyyy-MM-dd}`: you can adjust the temporal offset by adding or subtracting days, months, or years. Make sure you use the same order for each of the modifiers (ie, days must be left of months). **You can optionally specify a custom format using yyyy or yy to represent the year, MM or MMM for the month and dd or d for the day.**
=> Format dates

Dockerfile
I completely missed that we need cat in the mittens image for the readiness/liveness check.
And scratch doesn't come with it. Reverting back to alpine.
=> Use alpine. scratch doesn't come with cat.

pkg/warmup/warmup.go
Adds more readable logging outputs _**for HTTP and gRPC**_.
#148
```shell
~/repos/mittens 20s ❯ make -B unit-tests    
go: downloading github.com/jhump/protoreflect v1.8.2
go: downloading google.golang.org/grpc v1.36.0
go: downloading github.com/fullstorydev/grpcurl v1.8.0
go: downloading github.com/stretchr/testify v1.7.0
?       mittens [no test files]
?       mittens/cmd     [no test files]
ok      mittens/cmd/flags       0.266s
?       mittens/fixture [no test files]
ok      mittens/pkg/grpc        0.230s
ok      mittens/pkg/http        0.210s
ok      mittens/pkg/placeholders        0.584s
?       mittens/pkg/probe       [no test files]
?       mittens/pkg/response    [no test files]
ok      mittens/pkg/safe        0.307s
ok      mittens/pkg/util        0.459s
? …
```
=> Add more structure to response logging

cmd/root.go
- fmt.Errorf is not a function to print error. it make and return error.
- run() function does return no error, so change to print error using
log.Printf
In run() function, some errors made by fmt.Errors are not used. 
run() funcions does not return error, so errors should print using log.Printf if it need.
N/A
=> fix: change no effect code to log.Printf

Dockerfile
For some reason tests are failing with 16. Downgrading temporarily to 14 until we figure out what's wrong.
=> Downgrade builder docker image to go 14

cmd/root.go, internal/pkg/warmup/target.go
The headers were passed only in warmup calls and not health check calls, it lead to problems if there was a need to pass client info in headers grpc reflections calls or even health checks.
Let me know if you think its not valid case to pass request headers.
=> Pass headers in health check too

docs/about/getting-started.md, internal/pkg/grpc/client.go, internal/pkg/http/client.go, internal/pkg/http/client_test.go, internal/pkg/util/util.go, internal/pkg/util/util_test.go, internal/pkg/warmup/target.go, internal/pkg/warmup/warmup.go
Http headers sent during warmup phase would allow placeholders replacement (every line of sent http headers would go thru InterpolatePlaceholders())
https://github.com/ExpediaGroup/mittens/issues/204
=> Interpolate headers (use placeholders in http headers)

.github/workflows/go.yml, Dockerfile, docs/installation/building.md, go.mod, go.sum
- Bump dependencies
- Upgrade to go 1.18
- Bump base docker image (alpine)
=> Bump more dependencies and go version

internal/pkg/grpc/client.go
- `grpc.WithInsecure` is deprecated. Replacing with `withTransportCredentials`
=> Fix deprecated usage of withInsecure

internal/pkg/grpc/client.go
Currently insecure mode is not working with tls connection properly.
Added support for ignoring certificate similar to how http warmup behaves.
[#249](https://github.com/ExpediaGroup/mittens/issues/249)
=> Ignore certificate in insecure mode

.github/workflows/go.yml, .gitignore, Dockerfile, README.md, docs/installation/building.md, go.mod
- Update github action to use go 21
=> Update github action to use go 21

internal/pkg/http/client.go, internal/pkg/http/client_test.go, internal/pkg/http/utils.go, internal/pkg/http/utils_test.go, test/root_test.go
Mittens requests are recycled within the requests channel. Once the body i/o reader was closed, succeeding requests were not successful.
Currently mittens is broken due to an bug introduced in v1.46. During the processing of requests an i/o reader is passed to the client which leads to EOF errors on server side when the same request body is read the 2nd time. Hence only the first request of a warm-up succeeds and all others fail.  This should only affect configurations using POST data, but this needs to be fixed.
=> fix: fixes EOF error when having HTTP POST requests

internal/pkg/grpc/client.go
This PR fixes bug https://github.com/ExpediaGroup/mittens/issues/354
Regression tested manually against a grpc server.
https://github.com/ExpediaGroup/mittens/issues/354
=> Fix: Grpc timeout not set for warmup requests (#354)
